spring.application.name=restaurante_api

spring.datasource.url=jdbc:postgresql://localhost:5432/db_restaurante
spring.datasource.username=postgres
spring.datasource.password=fevereiro25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mercadopago.access-token=TEST-6721731876046225-040120-0073b34b7f594a193db52b91b8346a34-578716652
jwt.secret=restaurante-api-secreta-2026-nao-compartilhe-nunca