spring.application.name=restaurante_api

spring.datasource.url=jdbc:postgresql://localhost:5432/db_restaurante
spring.datasource.username=postgres
spring.datasource.password=fevereiro25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true